---
- name: Validate NFS client package, validate NFS mount
  hosts: ibisbx-app 
  tasks:
    - name: Validate nfs-utils is installed
      yum:
        name: nfs-utils
        state: present

    - name: Validate NFS mount
      mount: 
        path: "{{ mountpoint }}" 
        src: "{{ nfsserver }}:{{ export }}" 
        state: mounted
        fstype: nfs4
        opts: "x-systemd.automount,x-systemd.device-timeout=10,timeo=15"

#Comment


